### ISSUE TITLE
Gooood

### ISSUE THREAD

**Issue by 1995parham** [SamanFekri/DB_Filler#1]
ایول چ باحاله 👍 
برای تمرین دی بی هست ?

**Comment by SamanFekri** [comment]
خيلي احمقه بايد بهترش كنم الان وقت ندارم
قصدم اينه كه ساختار create table رو بديم خودش بسازه
و ممنون بابت توجهت
I m so zogh karde

**Comment by SajadAzami** [comment]
یه کاری کن تا پروژه آماده شه دیگه ما زحمت جدول ساختن نکشیم :laughing:

**Comment by SamanFekri** [comment]
سجاد اعظمي از كجا يهو پيداش شد ؟

**Comment by 1995parham** [comment]
هم گروهی آزت هست دیگر :)
خوبه دیگه چت روم شده

**Comment by SamanFekri** [comment]
آقا من فكر كردم تو ايميلم يهو از وسط گيت در اومدم واسه همين تعجب كردم سجاد ام جواب داد

**Comment by SajadAzami** [comment]
خلاصه حواست باشه سامان، من به ایمیلاتم دسترسی دارم :smile:
